# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/2.8.12.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/2.8.12.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/local/Cellar/cmake/2.8.12.2/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/diegocaro/Dropbox/research/temporalgraph/tgs-index

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/diegocaro/Research/temporalgraph/tgs-index

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/2.8.12.2/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/2.8.12.2/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/diegocaro/Research/temporalgraph/tgs-index/CMakeFiles /Users/diegocaro/Research/temporalgraph/tgs-index/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/diegocaro/Research/temporalgraph/tgs-index/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Objs

# Build rule for target.
Objs: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Objs
.PHONY : Objs

# fast build rule for target.
Objs/fast:
	$(MAKE) -f CMakeFiles/Objs.dir/build.make CMakeFiles/Objs.dir/build
.PHONY : Objs/fast

#=============================================================================
# Target rules for targets named benchmark

# Build rule for target.
benchmark: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 benchmark
.PHONY : benchmark

# fast build rule for target.
benchmark/fast:
	$(MAKE) -f CMakeFiles/benchmark.dir/build.make CMakeFiles/benchmark.dir/build
.PHONY : benchmark/fast

#=============================================================================
# Target rules for targets named benchmark2

# Build rule for target.
benchmark2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 benchmark2
.PHONY : benchmark2

# fast build rule for target.
benchmark2/fast:
	$(MAKE) -f CMakeFiles/benchmark2.dir/build.make CMakeFiles/benchmark2.dir/build
.PHONY : benchmark2/fast

#=============================================================================
# Target rules for targets named create

# Build rule for target.
create: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 create
.PHONY : create

# fast build rule for target.
create/fast:
	$(MAKE) -f CMakeFiles/create.dir/build.make CMakeFiles/create.dir/build
.PHONY : create/fast

#=============================================================================
# Target rules for targets named exp-query

# Build rule for target.
exp-query: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 exp-query
.PHONY : exp-query

# fast build rule for target.
exp-query/fast:
	$(MAKE) -f CMakeFiles/exp-query.dir/build.make CMakeFiles/exp-query.dir/build
.PHONY : exp-query/fast

arraysort.o: arraysort.cpp.o
.PHONY : arraysort.o

# target to build an object file
arraysort.cpp.o:
	$(MAKE) -f CMakeFiles/Objs.dir/build.make CMakeFiles/Objs.dir/arraysort.cpp.o
.PHONY : arraysort.cpp.o

arraysort.i: arraysort.cpp.i
.PHONY : arraysort.i

# target to preprocess a source file
arraysort.cpp.i:
	$(MAKE) -f CMakeFiles/Objs.dir/build.make CMakeFiles/Objs.dir/arraysort.cpp.i
.PHONY : arraysort.cpp.i

arraysort.s: arraysort.cpp.s
.PHONY : arraysort.s

# target to generate assembly for a file
arraysort.cpp.s:
	$(MAKE) -f CMakeFiles/Objs.dir/build.make CMakeFiles/Objs.dir/arraysort.cpp.s
.PHONY : arraysort.cpp.s

benchmark.o: benchmark.cpp.o
.PHONY : benchmark.o

# target to build an object file
benchmark.cpp.o:
	$(MAKE) -f CMakeFiles/benchmark.dir/build.make CMakeFiles/benchmark.dir/benchmark.cpp.o
.PHONY : benchmark.cpp.o

benchmark.i: benchmark.cpp.i
.PHONY : benchmark.i

# target to preprocess a source file
benchmark.cpp.i:
	$(MAKE) -f CMakeFiles/benchmark.dir/build.make CMakeFiles/benchmark.dir/benchmark.cpp.i
.PHONY : benchmark.cpp.i

benchmark.s: benchmark.cpp.s
.PHONY : benchmark.s

# target to generate assembly for a file
benchmark.cpp.s:
	$(MAKE) -f CMakeFiles/benchmark.dir/build.make CMakeFiles/benchmark.dir/benchmark.cpp.s
.PHONY : benchmark.cpp.s

benchmark2.o: benchmark2.cpp.o
.PHONY : benchmark2.o

# target to build an object file
benchmark2.cpp.o:
	$(MAKE) -f CMakeFiles/benchmark2.dir/build.make CMakeFiles/benchmark2.dir/benchmark2.cpp.o
.PHONY : benchmark2.cpp.o

benchmark2.i: benchmark2.cpp.i
.PHONY : benchmark2.i

# target to preprocess a source file
benchmark2.cpp.i:
	$(MAKE) -f CMakeFiles/benchmark2.dir/build.make CMakeFiles/benchmark2.dir/benchmark2.cpp.i
.PHONY : benchmark2.cpp.i

benchmark2.s: benchmark2.cpp.s
.PHONY : benchmark2.s

# target to generate assembly for a file
benchmark2.cpp.s:
	$(MAKE) -f CMakeFiles/benchmark2.dir/build.make CMakeFiles/benchmark2.dir/benchmark2.cpp.s
.PHONY : benchmark2.cpp.s

create.o: create.cpp.o
.PHONY : create.o

# target to build an object file
create.cpp.o:
	$(MAKE) -f CMakeFiles/create.dir/build.make CMakeFiles/create.dir/create.cpp.o
.PHONY : create.cpp.o

create.i: create.cpp.i
.PHONY : create.i

# target to preprocess a source file
create.cpp.i:
	$(MAKE) -f CMakeFiles/create.dir/build.make CMakeFiles/create.dir/create.cpp.i
.PHONY : create.cpp.i

create.s: create.cpp.s
.PHONY : create.s

# target to generate assembly for a file
create.cpp.s:
	$(MAKE) -f CMakeFiles/create.dir/build.make CMakeFiles/create.dir/create.cpp.s
.PHONY : create.cpp.s

exp-query.o: exp-query.cpp.o
.PHONY : exp-query.o

# target to build an object file
exp-query.cpp.o:
	$(MAKE) -f CMakeFiles/exp-query.dir/build.make CMakeFiles/exp-query.dir/exp-query.cpp.o
.PHONY : exp-query.cpp.o

exp-query.i: exp-query.cpp.i
.PHONY : exp-query.i

# target to preprocess a source file
exp-query.cpp.i:
	$(MAKE) -f CMakeFiles/exp-query.dir/build.make CMakeFiles/exp-query.dir/exp-query.cpp.i
.PHONY : exp-query.cpp.i

exp-query.s: exp-query.cpp.s
.PHONY : exp-query.s

# target to generate assembly for a file
exp-query.cpp.s:
	$(MAKE) -f CMakeFiles/exp-query.dir/build.make CMakeFiles/exp-query.dir/exp-query.cpp.s
.PHONY : exp-query.cpp.s

mywtmatrix.o: mywtmatrix.cpp.o
.PHONY : mywtmatrix.o

# target to build an object file
mywtmatrix.cpp.o:
	$(MAKE) -f CMakeFiles/Objs.dir/build.make CMakeFiles/Objs.dir/mywtmatrix.cpp.o
.PHONY : mywtmatrix.cpp.o

mywtmatrix.i: mywtmatrix.cpp.i
.PHONY : mywtmatrix.i

# target to preprocess a source file
mywtmatrix.cpp.i:
	$(MAKE) -f CMakeFiles/Objs.dir/build.make CMakeFiles/Objs.dir/mywtmatrix.cpp.i
.PHONY : mywtmatrix.cpp.i

mywtmatrix.s: mywtmatrix.cpp.s
.PHONY : mywtmatrix.s

# target to generate assembly for a file
mywtmatrix.cpp.s:
	$(MAKE) -f CMakeFiles/Objs.dir/build.make CMakeFiles/Objs.dir/mywtmatrix.cpp.s
.PHONY : mywtmatrix.cpp.s

tgs.o: tgs.cpp.o
.PHONY : tgs.o

# target to build an object file
tgs.cpp.o:
	$(MAKE) -f CMakeFiles/Objs.dir/build.make CMakeFiles/Objs.dir/tgs.cpp.o
.PHONY : tgs.cpp.o

tgs.i: tgs.cpp.i
.PHONY : tgs.i

# target to preprocess a source file
tgs.cpp.i:
	$(MAKE) -f CMakeFiles/Objs.dir/build.make CMakeFiles/Objs.dir/tgs.cpp.i
.PHONY : tgs.cpp.i

tgs.s: tgs.cpp.s
.PHONY : tgs.s

# target to generate assembly for a file
tgs.cpp.s:
	$(MAKE) -f CMakeFiles/Objs.dir/build.make CMakeFiles/Objs.dir/tgs.cpp.s
.PHONY : tgs.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... Objs"
	@echo "... benchmark"
	@echo "... benchmark2"
	@echo "... create"
	@echo "... edit_cache"
	@echo "... exp-query"
	@echo "... rebuild_cache"
	@echo "... arraysort.o"
	@echo "... arraysort.i"
	@echo "... arraysort.s"
	@echo "... benchmark.o"
	@echo "... benchmark.i"
	@echo "... benchmark.s"
	@echo "... benchmark2.o"
	@echo "... benchmark2.i"
	@echo "... benchmark2.s"
	@echo "... create.o"
	@echo "... create.i"
	@echo "... create.s"
	@echo "... exp-query.o"
	@echo "... exp-query.i"
	@echo "... exp-query.s"
	@echo "... mywtmatrix.o"
	@echo "... mywtmatrix.i"
	@echo "... mywtmatrix.s"
	@echo "... tgs.o"
	@echo "... tgs.i"
	@echo "... tgs.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

